LYRICS = [
    "Christmas, Christmas",
    "Christmas, Christmas, CHRISTMAS",
    "Christmas CHRISTMAS",
    "Christmas, Christmas",
    "It's about Christmas",
    "I don't know if you've noticed, but the weather's got rather cold",
    "That's becuase in the northern hemisphere of the Earth it's Winter",
    "and that's when it gets cold.",
    "I was collecting money for charity (a Christmas charity)",
    "then what flies over me? (a pigeon)",
    "and it wasn't lucky, no it was just yucky",
    "and I got Christmas on My Face",
    "a terrible case of Xmas",
    "I got Christmas on My Face",
    "it's terrible terrible terrible terrible terribly good.",
    "Yule tide, YULE LOG",
    "the nativity, holly, MISTLETOE",
    "Brussel Sprouts",
    "The Exchange of Gifts",
    "Santa (Christmas is Here)".
    "AFRICA",
    "(gonna tell you about xmas whilst mainting a rhythm)",
    "It's a Christmas condition for insufficient nutrition",
    "consult your physician for additional information.",
    "I was just being honest about someone's new sweater (it would rub on boxing day)",
    "he took it the wrong way, (you told him that it looked gay)",
    "I only implied that",
    "but he's gon' open up a can of Christmas on My Face",
    "a terrible case of Xmas",
    "I got Christmas on My Face",
    "it's terrible terrible terrible terrible terrible.",
    "Christmas on My Face",
    "a terrible case of Xmas",
    "I got Christmas on My Face",
    "it's terrible terrible terrible terrible terribly good.",
    "Seriously, have you thought about the dead ones?",
    "The ones from the flu, the drink-drivers too",
    "Oh what about you? (WHAT ARE YOU GONNA DO?)",
    "I've got Christmas on My Face",
    "a terrible case of Xmas",
    "I got Christmas on My Face",
    "it's terrible terrible terrible terrible terrible.",
    "I got Christmas on My Face",
    "a terrible case of Xmas",
    "I got Christmas on My Face",
    "it's terrible terrible terrible terrible terrible.",
    "I got Christmas on My Face",
    "a terrible case of Xmas",
    "I got Christmas on My Face",
    "it's terrible terrible terrible terrible terrible.",
    "Christmas on My Face",
    "a terrible case of Xmas",
    "I got Christmas on My Face",
    "it's terrible terrible terrible terrible terribly good.",
    "Thanks a lot."
]